spring:
  application:
    name: linknest-backend
  profiles:
    group:
      dev: [dev-config, commons, secret]
      prod: [prod-config, commons, secret]

--- #commons 공통 설정
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: commons
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        show_sql: true

app:
  jwt:
    issuer: linknest
    audience: linknest-client
    access-exp-minutes: 15
    refresh-exp-days: 7
    header: Authorization
    prefix: Bearer
    clock-skew-seconds: 60

--- #dev-config
spring:
  config:
    activate:
      on-profile: dev-config
  datasource:
    url: jdbc:mysql://localhost:3310/linknest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  data:
    redis:
      host: localhost
      port: 6380
      timeout: 5000

app:
  frontend:
    oauth2-success-redirect: "http://localhost:5173/redirect"

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: debug
    org.hibernate.SQL: warn
    org.hibernate.type: warn
    com.example: debug

--- #prod-config
spring:
  config:
    activate:
      on-profile: prod-config

logging:
  level:
    root: warn
    org.springframework.web: warn
    org.springframework.security: warn
    org.hibernate.SQL: warn
    org.hibernate.type: warn
    com.example: info